ruby '2.4.0'
source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-activerecord'
gem 'pg'
gem 'sinatra-asset-pipeline'
gem 'warden'
gem 'nokogiri'
gem 'httparty'
gem 'slim'
gem 'thin'
gem 'sinatra-contrib'
gem 'sinatra-flash'
gem 'sinatra-partial'
gem 'bcrypt'
gem 'rack_csrf'
gem 'auto_excerpt'
