# config/app.yml for rails-settings-cached
defaults: &defaults
  ring_name: "Friendship Circle"
  ring_description: "Default description goes here."

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
